create table if not exists ldap_directory_access_chart_tree(
ldap_directory_access_id Integer not null,
view_tree_effective_date varchar(255) null,
view_tree_code Integer null,
view_tree_description varchar(255) null,
access_chart1 varchar(255) null,
access_chart1_desc varchar(255) null,
access_chart2 varchar(255) null,
access_chart2_desc varchar(255) null,
access_chart3 varchar(255) null,
access_chart3_desc varchar(255) null,
access_chart4 varchar(255) null,
access_chart4_desc varchar(255) null,
access_chart5 varchar(255) null,
access_chart5_desc varchar(255) null,
access_chart6 varchar(255) null,
access_chart6_desc varchar(255) null,
access_chart7 varchar(255) null,
access_chart7_desc varchar(255) null,
creation_date varchar(255) null,
modified_date varchar(255) null,
entity_state varchar(255) null,
constraint ldap_directory_access_chart_tree_pk primary key(ldap_directory_access_id));